name: Build Anki CSV

on:
  push:
    paths:
      - "x.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run script
        run: python convert.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: anki-csv
          path: anki.csv
